export const DEFAULT_AUTO_COMPACT_THRESHOLD = 0.8;
export const MIN_AUTO_COMPACT_THRESHOLD_PERCENT = 1;
export const MAX_AUTO_COMPACT_THRESHOLD_PERCENT = 100;
export const PERCENT_SCALE = 100;
export const MAX_NOTICE_DETAIL_CHARS = 240;
export const MAX_REMEMBERED_SESSIONS = 32;
export const STILL_COMPACTING_AFTER_MS = 60_000;
