import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import {
  decodeAgentImage,
  decodeAvatarAnimation,
  encodeAgentImage,
  getPngDimensions,
} from "./pngCodec";
import {
  AgentSnapshotError,
  MAX_SNAPSHOT_AVATAR_ANIMATION_BYTES,
  MAX_SNAPSHOT_IMAGE_DIMENSION,
  MAX_SNAPSHOT_IMAGE_PIXELS,
  MAX_SNAPSHOT_PNG_BYTES,
  MAX_SNAPSHOT_PNG_CHUNKS,
  SNAPSHOT_FORMAT,
  SNAPSHOT_VERSION,
  type SnapshotV1,
} from "./schema";

const signature = Uint8Array.from([137, 80, 78, 71, 13, 10, 26, 10]);
const encoder = new TextEncoder();

function crc32(bytes: Uint8Array): number {
  let crc = 0xffffffff;
  for (const byte of bytes) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit += 1)
      crc = crc & 1 ? 0xedb88320 ^ (crc >>> 1) : crc >>> 1;
  }
  return (crc ^ 0xffffffff) >>> 0;
}

function chunk(type: string, data = new Uint8Array()): Uint8Array {
  const result = new Uint8Array(data.length + 12);
  new DataView(result.buffer).setUint32(0, data.length);
  result.set(encoder.encode(type), 4);
  result.set(data, 8);
  new DataView(result.buffer).setUint32(
    result.length - 4,
    crc32(result.subarray(4, -4)),
  );
  return result;
}

function concat(...parts: Uint8Array[]): Uint8Array {
  const result = new Uint8Array(
    parts.reduce((length, part) => length + part.length, 0),
  );
  let offset = 0;
  for (const part of parts) {
    result.set(part, offset);
    offset += part.length;
  }
  return result;
}

function pngWithDimensions(
  width: number,
  height: number,
  ...extraChunks: Uint8Array[]
): Uint8Array {
  const ihdr = new Uint8Array(13);
  new DataView(ihdr.buffer).setUint32(0, width);
  new DataView(ihdr.buffer).setUint32(4, height);
  ihdr.set([8, 6, 0, 0, 0], 8);
  return concat(signature, chunk("IHDR", ihdr), ...extraChunks, chunk("IEND"));
}

function png(...extraChunks: Uint8Array[]): Uint8Array {
  return pngWithDimensions(1, 1, ...extraChunks);
}

function base64(bytes: Uint8Array): string {
  let binary = "";
  for (let offset = 0; offset < bytes.length; offset += 0x8000) {
    binary += String.fromCharCode(...bytes.subarray(offset, offset + 0x8000));
  }
  return btoa(binary);
}

function textChunk(value: string, keyword = "buzz_agent_snapshot"): Uint8Array {
  return chunk("tEXt", encoder.encode(`${keyword}\0${value}`));
}

function manifest(overrides: Record<string, unknown> = {}): SnapshotV1 {
  return {
    format: SNAPSHOT_FORMAT,
    version: SNAPSHOT_VERSION,
    definition: { name: "研究助手", systemPrompt: "Be careful." },
    profile: { displayName: "Research Assistant" },
    memory: { level: "none", entries: [] },
    ...overrides,
  };
}

function encodedManifest(value: unknown): Uint8Array {
  return textChunk(base64(encoder.encode(JSON.stringify(value))));
}

function expectCode(
  run: () => unknown,
  code: AgentSnapshotError["code"],
): void {
  try {
    run();
    throw new Error("expected operation to throw");
  } catch (error) {
    expect(error).toBeInstanceOf(AgentSnapshotError);
    expect((error as AgentSnapshotError).code).toBe(code);
  }
}

describe("buzz-agent-snapshot PNG codec", () => {
  it("returns dimensions from a fully validated PNG", () => {
    expect(getPngDimensions(pngWithDimensions(321, 654))).toEqual({
      width: 321,
      height: 654,
    });
    expect(() => getPngDimensions(Uint8Array.from([1, 2, 3]))).toThrow(
      "Invalid PNG signature",
    );
  });
  it("round trips animated avatar bytes outside snapshot JSON", () => {
    const animation = {
      bytes: Uint8Array.from([26, 69, 223, 163]),
      mimeType: "video/webm" as const,
      alphaMode: "stacked" as const,
    };
    const input = png();
    const encoded = encodeAgentImage(input, manifest(), animation);

    expect(decodeAgentImage(encoded)).toEqual(manifest());
    expect(decodeAvatarAnimation(encoded)).toEqual(animation);
  });

  it("decodes the canonical config-only fixture generated by Buzz", () => {
    const fixture = new Uint8Array(
      readFileSync(
        resolve(
          process.cwd(),
          "src/features/agents/agent-snapshot/fixtures/buzz-v1-config-only.agent.png",
        ),
      ),
    );

    const decoded = decodeAgentImage(fixture);

    expect(decoded).toMatchObject({
      format: "buzz-agent-snapshot",
      version: 1,
      definition: {
        name: "Test Agent Display",
        systemPrompt: "You are a test agent.",
        runtime: "goose",
        model: "claude-opus-4",
        provider: "anthropic",
      },
      profile: {
        displayName: "Test Agent Display",
        avatarUrl: "https://example.com/avatar.png",
      },
      memory: { level: "none" },
    });
    expect(decoded.memory?.entries ?? []).toEqual([]);
    expect(JSON.stringify(decoded)).not.toMatch(
      /nsec1secret|secret123|SENTINEL_|\/usr\/local\/bin\/acp/,
    );
  });

  it("keeps Berd's conformance export semantically decodable", () => {
    const fixture = new Uint8Array(
      readFileSync(
        resolve(
          process.cwd(),
          "src/features/agents/agent-snapshot/fixtures/berd-v1-config-only.agent.png",
        ),
      ),
    );

    expect(decodeAgentImage(fixture)).toMatchObject({
      format: "buzz-agent-snapshot",
      version: 1,
      definition: {
        name: "Berd Compatibility Agent",
        systemPrompt: "Validate Buzz interoperability.",
        provider: "test-provider",
        model: "test-model",
      },
    });
    expect(decodeAgentImage(fixture).memory).toBeUndefined();
  });

  it("encodes and decodes a UTF-8 v1 snapshot while preserving image chunks", () => {
    const source = png(chunk("IDAT", Uint8Array.from([1, 2, 3])));
    const encoded = encodeAgentImage(source, manifest());

    expect(decodeAgentImage(encoded)).toEqual(manifest());
    expect(encoded).toContain(1);
    expect(encoded).toContain(2);
    expect(encoded).toContain(3);
  });

  it("replaces an existing snapshot rather than creating a duplicate", () => {
    const once = encodeAgentImage(png(), manifest());
    const replacement = manifest({ profile: { displayName: "Replacement" } });
    expect(decodeAgentImage(encodeAgentImage(once, replacement))).toEqual(
      replacement,
    );
  });

  it("rejects an ordinary PNG and duplicate snapshot chunks", () => {
    expectCode(() => decodeAgentImage(png()), "missing-snapshot");
    const embedded = encodedManifest(manifest());
    expectCode(
      () => decodeAgentImage(png(embedded, embedded)),
      "duplicate-snapshot",
    );
  });

  it("rejects wrong magic, truncated chunks, missing IEND, and bad CRC", () => {
    expectCode(() => decodeAgentImage(new Uint8Array()), "invalid-png");
    expectCode(
      () => decodeAgentImage(concat(signature, Uint8Array.from([0, 0, 0]))),
      "invalid-png",
    );
    expectCode(
      () =>
        decodeAgentImage(concat(signature, chunk("IHDR", new Uint8Array(13)))),
      "invalid-png",
    );
    const damaged = png(encodedManifest(manifest()));
    damaged[20] ^= 1;
    expectCode(() => decodeAgentImage(damaged), "invalid-png");
  });

  it("rejects unsafe decoded image dimensions", () => {
    expectCode(
      () =>
        decodeAgentImage(pngWithDimensions(0, 1, encodedManifest(manifest()))),
      "invalid-png",
    );
    expectCode(
      () =>
        decodeAgentImage(
          pngWithDimensions(
            MAX_SNAPSHOT_IMAGE_DIMENSION + 1,
            1,
            encodedManifest(manifest()),
          ),
        ),
      "invalid-png",
    );
    expectCode(
      () =>
        decodeAgentImage(
          pngWithDimensions(
            MAX_SNAPSHOT_IMAGE_PIXELS,
            MAX_SNAPSHOT_IMAGE_PIXELS,
            encodedManifest(manifest()),
          ),
        ),
      "invalid-png",
    );
  });

  it("rejects animations the native importer cannot restore", () => {
    expectCode(
      () =>
        encodeAgentImage(png(), manifest(), {
          bytes: new Uint8Array(MAX_SNAPSHOT_AVATAR_ANIMATION_BYTES + 1),
          mimeType: "video/mp4",
        }),
      "too-large",
    );
  });

  it("rejects oversized animation chunks while decoding", () => {
    const oversized = new Uint8Array(MAX_SNAPSHOT_AVATAR_ANIMATION_BYTES + 2);
    expectCode(
      () => decodeAvatarAnimation(png(chunk("bdAV", oversized))),
      "too-large",
    );
  });

  it("rejects PNGs with excessive chunk counts", () => {
    const extras = Array.from({ length: MAX_SNAPSHOT_PNG_CHUNKS }, () =>
      chunk("aaAA"),
    );
    expectCode(
      () => decodeAgentImage(png(...extras, encodedManifest(manifest()))),
      "invalid-png",
    );
  });

  it("enforces the 10 MiB input cap before parsing", () => {
    expectCode(
      () => decodeAgentImage(new Uint8Array(MAX_SNAPSHOT_PNG_BYTES + 1)),
      "too-large",
    );
  });

  it("accepts a near-limit decoded PNG avatar data URL", () => {
    const avatarBytes = new Uint8Array(2 * 1024 * 1024);
    avatarBytes.set(signature);
    const avatarDataUrl = `data:image/png;base64,${base64(avatarBytes)}`;
    expect(() =>
      encodeAgentImage(
        png(),
        manifest({ profile: { displayName: "Test", avatarDataUrl } }),
      ),
    ).not.toThrow();
  });

  it("rejects invalid base64, UTF-8, and JSON independently", () => {
    expectCode(
      () => decodeAgentImage(png(textChunk("!!!!"))),
      "invalid-base64",
    );
    expectCode(
      () => decodeAgentImage(png(textChunk(base64(Uint8Array.from([0xff]))))),
      "invalid-utf8",
    );
    expectCode(
      () => decodeAgentImage(png(textChunk(base64(encoder.encode("{"))))),
      "invalid-json",
    );
  });

  it("rejects wrong format, unsupported version, and empty names", () => {
    expectCode(
      () =>
        decodeAgentImage(png(encodedManifest(manifest({ format: "other" })))),
      "wrong-format",
    );
    expectCode(
      () => decodeAgentImage(png(encodedManifest(manifest({ version: 2 })))),
      "unsupported-version",
    );
    expectCode(
      () =>
        decodeAgentImage(
          png(
            encodedManifest(
              manifest({ definition: { name: " " }, profile: {} }),
            ),
          ),
        ),
      "invalid-snapshot",
    );
  });

  it("accepts definition-name fallback, unknown v1 fields, and memory-bearing snapshots", () => {
    const value = manifest({
      definition: { name: "Fallback", futureDefinitionField: true },
      profile: { futureProfileField: 42 },
      memory: {
        level: "core",
        entries: [{ slug: "core", body: "private" }],
        futureMemoryField: "ok",
      },
      futureEnvelopeField: { enabled: true },
    });
    expect(decodeAgentImage(png(encodedManifest(value)))).toEqual(value);
  });

  it("does not treat zTXt, iTXt, or another keyword as a snapshot", () => {
    const payload = encoder.encode("buzz_agent_snapshot\0anything");
    expectCode(
      () =>
        decodeAgentImage(
          png(
            chunk("zTXt", payload),
            chunk("iTXt", payload),
            textChunk("anything", "other"),
          ),
        ),
      "missing-snapshot",
    );
  });
});
