import type { ProjectModel } from "../types.ts";
import { table } from "./markdown.ts";

export function apisDoc(model: ProjectModel): string {
  const workspaceOf = new Map(model.files.map((file) => [file.path, file.workspace ?? "(root)"]));
  const tests = new Set(model.files.filter((file) => file.kind === "test").map((file) => file.path));
  const apis = model.apis.filter((api) => !tests.has(api.file));
  const groups = [...new Set(apis.map((api) => workspaceOf.get(api.file) ?? "(root)"))].sort();
  const sections = groups.flatMap((group) => [
    `## ${group}`,
    "",
    table(
      ["Method", "Path", "Kind", "Handler", "Where"],
      apis.filter((api) => (workspaceOf.get(api.file) ?? "(root)") === group).map((api) => [api.method, api.path, api.source, api.handler ?? "—", `${api.file}:${api.line}`]),
    ),
    "",
  ]);
  return ["# APIs", "", "Routes found in code and contract entries declared as `{ method, path }`. Generated by Weave.", "", ...(sections.length > 0 ? sections : ["No APIs found.", ""])].join("\n");
}
