import type { ProjectModel, Workspace } from "../types.ts";
import { table } from "./markdown.ts";

const TOP_EXTERNAL_PACKAGES = 20;

function layerSummary(model: ProjectModel, workspace: Workspace): string {
  const layers = model.architecture.find((entry) => entry.workspace === workspace.name)?.layers ?? {};
  return Object.entries(layers).sort((a, b) => a[0].localeCompare(b[0])).map(([layer, count]) => `${layer} ${count}`).join(", ") || "none";
}

export function architectureDoc(model: ProjectModel): string {
  const { repository, stack } = model;
  const workspaces = [...model.applications, ...model.packages];
  return [
    "# Architecture",
    "",
    `Generated by Weave from the repository (model revision ${model.revision}${repository.head ? `, commit ${repository.head.slice(0, 12)}` : ""}). Do not edit by hand.`,
    "",
    "## Stack",
    "",
    `- Languages: ${stack.languages.join(", ") || "unknown"}`,
    `- Frameworks: ${stack.frameworks.join(", ") || "none detected"}`,
    `- Package manager: ${stack.packageManager ?? "none"}`,
    "",
    "## Workspaces",
    "",
    table(
      ["Name", "Kind", "Directory", "Layers (files)", "Depends on", "Entrypoints"],
      workspaces.map((workspace) => [workspace.name, workspace.kind, workspace.dir, layerSummary(model, workspace), workspace.internalDependencies.join(", ") || "—", workspace.entrypoints.join(", ") || "—"]),
    ),
    "",
    "## External packages",
    "",
    table(["Package", "Files importing it"], model.dependencies.external.slice(0, TOP_EXTERNAL_PACKAGES).map((entry) => [entry.name, String(entry.dependents)])),
    "",
    "## Size",
    "",
    `${model.files.length} files, ${model.symbols.length} symbols, ${model.dependencies.internal.length} internal imports, ${model.dependencies.calls.length} resolved calls, ${model.apis.length} API facts, ${model.events.length} events.`,
    "",
  ].join("\n");
}
