import type { ApiFact, ProjectModel } from "../types.ts";

const MAX_FLOW_DEPTH = 4;
const MAX_FLOW_NODES = 30;
const MAX_FLOWS = 50;

function forwardIndex(model: ProjectModel): ReadonlyMap<string, readonly string[]> {
  const index = new Map<string, string[]>();
  for (const call of model.dependencies.calls) index.set(call.from, [...(index.get(call.from) ?? []), call.to]);
  return index;
}

function handlerId(model: ProjectModel, api: ApiFact): string | null {
  const name = api.handler?.split(".").at(-1);
  if (!name) return null;
  const inFile = model.symbols.find((symbol) => symbol.file === api.file && (symbol.name === api.handler || symbol.name.endsWith(`.${name}`) || symbol.name === name));
  return inFile?.id ?? model.symbols.find((symbol) => symbol.name === name)?.id ?? null;
}

function flowLines(start: string, calls: ReadonlyMap<string, readonly string[]>): readonly string[] {
  const lines: string[] = [];
  const seen = new Set<string>();
  const visit = (id: string, depth: number) => {
    if (seen.has(id) || lines.length >= MAX_FLOW_NODES) return;
    seen.add(id);
    lines.push(`${"  ".repeat(depth)}- \`${id}\``);
    if (depth >= MAX_FLOW_DEPTH) return;
    for (const next of [...(calls.get(id) ?? [])].sort()) visit(next, depth + 1);
  };
  visit(start, 0);
  return lines;
}

export function dataFlowDoc(model: ProjectModel): string {
  const calls = forwardIndex(model);
  const eventsByFile = new Map<string, string[]>();
  for (const event of model.events) eventsByFile.set(event.file, [...(eventsByFile.get(event.file) ?? []), `${event.role} \`${event.name}\``]);
  const flows = model.apis.filter((api) => api.source === "route").slice(0, MAX_FLOWS).flatMap((api) => {
    const start = handlerId(model, api);
    if (!start) return [];
    const lines = flowLines(start, calls);
    const files = new Set(lines.map((line) => /`([^`#]+)#/.exec(line)?.[1] ?? ""));
    const events = [...files].flatMap((file) => eventsByFile.get(file) ?? []);
    return [`## ${api.method} ${api.path}`, "", ...lines, ...(events.length > 0 ? ["", `Events: ${[...new Set(events)].join(", ")}`] : []), ""];
  });
  return ["# Data flow", "", `From each route handler through resolved calls (up to ${MAX_FLOW_DEPTH} hops). Generated by Weave.`, "", ...(flows.length > 0 ? flows : ["No route handlers resolved.", ""])].join("\n");
}
