export const TRANSCRIPT_SELECTION_SURFACE_ATTRIBUTE =
  "data-transcript-selection-surface";
export const TRANSCRIPT_SELECTION_SURFACE_VALUE = "timeline";
export const TRANSCRIPT_SELECTION_SURFACE_SELECTOR = `[${TRANSCRIPT_SELECTION_SURFACE_ATTRIBUTE}="${TRANSCRIPT_SELECTION_SURFACE_VALUE}"]`;
export const TRANSCRIPT_SELECTION_SURFACE_ATTRIBUTES = {
  [TRANSCRIPT_SELECTION_SURFACE_ATTRIBUTE]: TRANSCRIPT_SELECTION_SURFACE_VALUE,
} as const;
